ConstraintDatabase resultCDB = resultCore.getContext();
ValueLookup valueLookup = resultCDB.getUnique(ValueLookup.class);
assertTrue(valueLookup.getEST(Term.createConstant("I1")) == 1);
assertTrue(valueLookup.getLST(Term.createConstant("I1")) == 10);
assertTrue(valueLookup.getEET(Term.createConstant("I1")) == 11);
assertTrue(valueLookup.getLET(Term.createConstant("I1")) == 15);
assertTrue(valueLookup.getEST(Term.createConstant("I2")) == 11);
assertTrue(valueLookup.getLST(Term.createConstant("I2")) == 15);
assertTrue(valueLookup.getEET(Term.createConstant("I2")) == 16);
assertTrue(valueLookup.getLET(Term.createConstant("I2")) == 20);
assertTrue(valueLookup.getEST(Term.createConstant("I3")) == 16);
assertTrue(valueLookup.getLST(Term.createConstant("I3")) == 20);
assertTrue(valueLookup.getEET(Term.createConstant("I3")) == 21);
assertTrue(valueLookup.getLET(Term.createConstant("I3")) == 25);
assertTrue(valueLookup.getEST(Term.createConstant("I4")) == 21);
assertTrue(valueLookup.getLST(Term.createConstant("I4")) == 25);
assertTrue(valueLookup.getEET(Term.createConstant("I4")) == 26);
assertTrue(valueLookup.getLET(Term.createConstant("I4")) == 30);
assertTrue(valueLookup.getEST(Term.createConstant("I5")) == 26);
assertTrue(valueLookup.getLST(Term.createConstant("I5")) == 30);
assertTrue(valueLookup.getEET(Term.createConstant("I5")) == 31);
assertTrue(valueLookup.getLET(Term.createConstant("I5")) == 40);
assertTrue(valueLookup.getEST(Term.createConstant("I6")) == 0);
assertTrue(valueLookup.getLST(Term.createConstant("I6")) == 10);
assertTrue(valueLookup.getEET(Term.createConstant("I6")) == 1);
assertTrue(valueLookup.getLET(Term.createConstant("I6")) == 10);
