ConstraintDatabase resultCDB = resultCore.getContext();
ValueLookup valueLookup = resultCDB.getUnique(ValueLookup.class);
assertTrue(resultCDB.contains(new AllenConstraint(Term.createConstant("I1"), Term.createConstant("I2"), TemporalRelation.Equals)));
assertTrue(valueLookup.getEST(Term.createConstant("I1")) == 30);
assertTrue(valueLookup.getLST(Term.createConstant("I1")) == 40);
assertTrue(valueLookup.getEET(Term.createConstant("I1")) == 50);
assertTrue(valueLookup.getLET(Term.createConstant("I1")) == 80);
assertTrue(valueLookup.getEST(Term.createConstant("I2")) == 30);
assertTrue(valueLookup.getLST(Term.createConstant("I2")) == 40);
assertTrue(valueLookup.getEET(Term.createConstant("I2")) == 50);
assertTrue(valueLookup.getLET(Term.createConstant("I2")) == 80);
