ConstraintDatabase resultCDB = resultCore.getContext();
ValueLookup valueLookup = resultCDB.getUnique(ValueLookup.class);
assertTrue(valueLookup.getEST(Term.createConstant("Iref")) == 10);
assertTrue(valueLookup.getLST(Term.createConstant("Iref")) == 10);
assertTrue(valueLookup.getEET(Term.createConstant("Iref")) == 20);
assertTrue(valueLookup.getLET(Term.createConstant("Iref")) == 20);
assertTrue(valueLookup.getEST(Term.createConstant("Iref")) == 10);
assertTrue(valueLookup.getLST(Term.createConstant("I1")) == 10);
assertTrue(valueLookup.getEET(Term.createConstant("I1")) == 15);
assertTrue(valueLookup.getLET(Term.createConstant("I1")) == 15);
assertTrue(valueLookup.getEST(Term.createConstant("I2")) == 10);
assertTrue(valueLookup.getLST(Term.createConstant("I2")) == 10);
assertTrue(valueLookup.getEET(Term.createConstant("I2")) == 15);
assertTrue(valueLookup.getLET(Term.createConstant("I2")) == 15);
