/* Generated By:JavaCC: Do not edit this line. DomainParser_v4Constants.java */
package org.spiderplan.representation.parser.domain_v4;
@SuppressWarnings("all")


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DomainParser_v4Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INCLUDE = 6;
  /** RegularExpression Id. */
  int EXECUTION = 7;
  /** RegularExpression Id. */
  int TEMPORAL = 8;
  /** RegularExpression Id. */
  int COST = 9;
  /** RegularExpression Id. */
  int OPTIMIZATION = 10;
  /** RegularExpression Id. */
  int MATH = 11;
  /** RegularExpression Id. */
  int SET = 12;
  /** RegularExpression Id. */
  int GRAPH = 13;
  /** RegularExpression Id. */
  int PROLOG = 14;
  /** RegularExpression Id. */
  int SPARQL = 15;
  /** RegularExpression Id. */
  int DOMAIN = 16;
  /** RegularExpression Id. */
  int GOAL = 17;
  /** RegularExpression Id. */
  int TASK = 18;
  /** RegularExpression Id. */
  int OBSERVATION = 19;
  /** RegularExpression Id. */
  int FINALLY = 20;
  /** RegularExpression Id. */
  int MINIZINC = 21;
  /** RegularExpression Id. */
  int RESOURCE = 22;
  /** RegularExpression Id. */
  int CONDITIONAL = 23;
  /** RegularExpression Id. */
  int IC = 24;
  /** RegularExpression Id. */
  int CONDITION = 25;
  /** RegularExpression Id. */
  int SAMPLING = 26;
  /** RegularExpression Id. */
  int CONFIGURATIONPLANNING = 27;
  /** RegularExpression Id. */
  int ROS = 28;
  /** RegularExpression Id. */
  int DBEXEC = 29;
  /** RegularExpression Id. */
  int RESOLVER = 30;
  /** RegularExpression Id. */
  int CAPACITY = 31;
  /** RegularExpression Id. */
  int INITIAL = 32;
  /** RegularExpression Id. */
  int SIMULATE = 33;
  /** RegularExpression Id. */
  int STATEMENT = 34;
  /** RegularExpression Id. */
  int OPERATOR = 35;
  /** RegularExpression Id. */
  int SIGNATURE = 36;
  /** RegularExpression Id. */
  int PRECONDITIONS = 37;
  /** RegularExpression Id. */
  int EFFECTS = 38;
  /** RegularExpression Id. */
  int ASSERTION = 39;
  /** RegularExpression Id. */
  int CONSTRAINTS = 40;
  /** RegularExpression Id. */
  int ROSPUBLISH = 41;
  /** RegularExpression Id. */
  int ROSSUBSCRIBE = 42;
  /** RegularExpression Id. */
  int ROSGOAL = 43;
  /** RegularExpression Id. */
  int REUSABLE = 44;
  /** RegularExpression Id. */
  int SOCKETS = 45;
  /** RegularExpression Id. */
  int ONTOLOGY = 46;
  /** RegularExpression Id. */
  int OP = 47;
  /** RegularExpression Id. */
  int CP = 48;
  /** RegularExpression Id. */
  int OBRACKET = 49;
  /** RegularExpression Id. */
  int CBRACKET = 50;
  /** RegularExpression Id. */
  int OBRACE = 51;
  /** RegularExpression Id. */
  int CBRACE = 52;
  /** RegularExpression Id. */
  int BAR = 53;
  /** RegularExpression Id. */
  int QPOINT = 54;
  /** RegularExpression Id. */
  int QMARKS = 55;
  /** RegularExpression Id. */
  int NON_COMPLEX_TERM = 56;
  /** RegularExpression Id. */
  int STRING = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":include\"",
    "\":execution\"",
    "\":temporal\"",
    "\":cost\"",
    "\":optimization\"",
    "\":math\"",
    "\":set\"",
    "\":graph\"",
    "\":prolog\"",
    "\":sparql\"",
    "\":domain\"",
    "\":goal\"",
    "\":task\"",
    "\":observation\"",
    "\":finally\"",
    "\":minizinc\"",
    "\":resource\"",
    "\":conditional\"",
    "\":ic\"",
    "\":condition\"",
    "\":sampling\"",
    "\":configuration-planning\"",
    "\":ros\"",
    "\":database-execution\"",
    "\":resolver\"",
    "\":capacity\"",
    "\":initial-context\"",
    "\":simulate\"",
    "\":statement\"",
    "\":operator\"",
    "\":signature\"",
    "\":preconditions\"",
    "\":effects\"",
    "\":assertion\"",
    "\":constraints\"",
    "\"publish\"",
    "\"subscribe\"",
    "\"actionlib\"",
    "\"reusable\"",
    "\":sockets\"",
    "\":ontology\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"|\"",
    "\"?\"",
    "\"\\\"\"",
    "<NON_COMPLEX_TERM>",
    "<STRING>",
  };

}
