/* Generated By:JavaCC: Do not edit this line. DomainParser_v4TokenManager.java */
package org.spiderplan.representation.parser.domain_v4;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.util.Collection;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.charset.*;
import java.io.IOException;
import org.spiderplan.representation.*;
import org.spiderplan.representation.types.*;
import org.spiderplan.representation.constraints.*;
import org.spiderplan.representation.constraints.ros.*;
import org.spiderplan.representation.constraints.VariableDomainRestriction.Relation;
import org.spiderplan.modules.solvers.Core;
import org.spiderplan.representation.logic.*;
import org.spiderplan.temporal.TemporalNetworkTools;
import org.spiderplan.tools.UniqueID;

/** Token Manager. */
public class DomainParser_v4TokenManager implements DomainParser_v4Constants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x400000000000000L) != 0L)
            return 14;
         if ((active0 & 0xffffffffc0L) != 0L)
         {
            jjmatchedKind = 71;
            return 15;
         }
         if ((active0 & 0x1000000000000L) != 0L)
            return 13;
         if ((active0 & 0x10000000000000L) != 0L || (active1 & 0x20L) != 0L)
            return 7;
         if ((active0 & 0x8000000000000L) != 0L)
            return 16;
         return -1;
      case 1:
         if ((active0 & 0xffffffffc0L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 1;
            return 15;
         }
         return -1;
      case 2:
         if ((active0 & 0x800000L) != 0L)
            return 15;
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 2;
            return 7;
         }
         if ((active0 & 0xfff77fffc0L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 2;
            return 15;
         }
         return -1;
      case 3:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 3;
            return 7;
         }
         if ((active0 & 0x18e00L) != 0L)
            return 15;
         if ((active0 & 0xfff77e71c0L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 3;
            return 15;
         }
         return -1;
      case 4:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 4;
            return 7;
         }
         if ((active0 & 0x1000L) != 0L)
            return 15;
         if ((active0 & 0xfff77e61c0L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 4;
            return 15;
         }
         return -1;
      case 5:
         if ((active0 & 0x200006000L) != 0L)
            return 15;
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 5;
            return 7;
         }
         if ((active0 & 0xfdf77e01c0L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 5;
            return 15;
         }
         return -1;
      case 6:
         if ((active0 & 0x4000020040L) != 0L)
            return 15;
         if ((active0 & 0xbdf77c0180L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 6;
            return 15;
         }
         if ((active0 & 0x8000000L) != 0L)
            return 7;
         return -1;
      case 7:
         if ((active0 & 0x14700c0100L) != 0L)
            return 15;
         if ((active0 & 0xa886700080L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 7;
            return 15;
         }
         if ((active0 & 0x101000000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 7;
            return 7;
         }
         return -1;
      case 8:
         if ((active0 & 0x800300080L) != 0L)
            return 15;
         if ((active0 & 0xa082400000L) != 0L)
         {
            if (jjmatchedPos != 8)
            {
               jjmatchedKind = 71;
               jjmatchedPos = 8;
            }
            return 15;
         }
         if ((active0 & 0x105000000L) != 0L)
         {
            if (jjmatchedPos != 8)
            {
               jjmatchedKind = 71;
               jjmatchedPos = 8;
            }
            return 7;
         }
         return -1;
      case 9:
         if ((active0 & 0x80000000L) != 0L)
            return 15;
         if ((active0 & 0xa000500000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 9;
            return 15;
         }
         if ((active0 & 0x106000000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 9;
            return 7;
         }
         if ((active0 & 0x1000000L) != 0L)
            return 7;
         return -1;
      case 10:
         if ((active0 & 0x8000100000L) != 0L)
            return 15;
         if ((active0 & 0x106000000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 10;
            return 7;
         }
         if ((active0 & 0x2000400000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 10;
            return 15;
         }
         return -1;
      case 11:
         if ((active0 & 0x2000400000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 11;
            return 15;
         }
         if ((active0 & 0x104000000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 11;
            return 7;
         }
         if ((active0 & 0x2000000L) != 0L)
            return 7;
         return -1;
      case 12:
         if ((active0 & 0x2000400000L) != 0L)
            return 15;
         if ((active0 & 0x104000000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 12;
            return 7;
         }
         return -1;
      case 13:
         if ((active0 & 0x104000000L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 13;
            return 7;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 61;
         return jjMoveStringLiteralDfa1_0(0x1000000000000000L, 0x0L);
      case 34:
         return jjStartNfaWithStates_0(0, 58, 14);
      case 35:
         return jjStopAtPos(0, 67);
      case 36:
         return jjStopAtPos(0, 68);
      case 40:
         return jjStopAtPos(0, 40);
      case 41:
         return jjStopAtPos(0, 41);
      case 42:
         return jjStopAtPos(0, 56);
      case 43:
         return jjStopAtPos(0, 54);
      case 44:
         return jjStopAtPos(0, 47);
      case 45:
         jjmatchedKind = 55;
         return jjMoveStringLiteralDfa1_0(0x20000000000000L, 0x0L);
      case 46:
         return jjStartNfaWithStates_0(0, 48, 13);
      case 47:
         return jjStartNfaWithStates_0(0, 52, 7);
      case 58:
         jjmatchedKind = 49;
         return jjMoveStringLiteralDfa1_0(0x4000000000000L, 0x0L);
      case 59:
         return jjStartNfaWithStates_0(0, 51, 16);
      case 60:
         jjmatchedKind = 62;
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L, 0x0L);
      case 61:
         return jjStopAtPos(0, 59);
      case 62:
         jjmatchedKind = 64;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2L);
      case 63:
         return jjStopAtPos(0, 66);
      case 91:
         return jjStopAtPos(0, 42);
      case 92:
         return jjStopAtPos(0, 57);
      case 93:
         return jjStopAtPos(0, 43);
      case 95:
         return jjStartNfaWithStates_0(0, 69, 7);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x82a0300200L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x4000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x4000000080L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x20000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x9000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x108000040L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x40400L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x1000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x2001402000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x54880000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0xc02000800L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x10100L, 0x0L);
      case 123:
         return jjStopAtPos(0, 44);
      case 124:
         return jjStopAtPos(0, 46);
      case 125:
         return jjStopAtPos(0, 45);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 61:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 50);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStopAtPos(1, 60);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(1, 63);
         else if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(1, 65);
         break;
      case 62:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStopAtPos(1, 53);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x20010400L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x54080900L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x400060000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000040L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x8080b0c200L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000403000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x203000000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x800009000L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000080L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x400004100L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x8080360000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x402000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
      case 115:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 23, 15);
         return jjMoveStringLiteralDfa3_0(active0, 0x210090200L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0xc00L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, 0L);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x20024000L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000080L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x300000L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 104:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 10, 15);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x4040000L);
      case 107:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 16, 15);
         break;
      case 108:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(3, 15, 15);
         return jjMoveStringLiteralDfa4_0(active0, 0x1002040L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x10080000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x1100L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L);
      case 115:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 15);
         return jjMoveStringLiteralDfa4_0(active0, 0x80c2000000L);
      case 116:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 9, 15);
         return jjMoveStringLiteralDfa4_0(active0, 0xb00000000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, 0L);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x1040400000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x4022000000L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000L);
      case 104:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 15);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x101304000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x410020000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x2208002100L);
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x800800c0L);
      case 122:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x508000000L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x40400000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x40L);
      case 103:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 13, 15);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x20040000L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000L);
      case 109:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 15);
         return jjMoveStringLiteralDfa6_0(active0, 0x880000000L);
      case 110:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 14, 15);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x8002080100L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x5004300080L);
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x8080000100L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L);
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000L);
      case 101:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(6, 6, 15);
         return jjMoveStringLiteralDfa7_0(active0, 0x814000000L);
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x2700080L);
      case 108:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(6, 27, 7);
         return jjMoveStringLiteralDfa7_0(active0, 0x140000000L);
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000L);
      case 115:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 38, 15);
         break;
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x420000000L);
      case 121:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(6, 17, 15);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa8_0(active0, 0x101000000L);
      case 98:
         return jjMoveStringLiteralDfa8_0(active0, 0x82000000L);
      case 99:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(7, 18, 15);
         break;
      case 101:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(7, 19, 15);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(7, 30, 15);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(7, 34, 15);
         break;
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0xa000000000L);
      case 108:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(7, 8, 15);
         return jjMoveStringLiteralDfa8_0(active0, 0x400000L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000L);
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x300080L);
      case 114:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(7, 28, 15);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 36, 15);
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000L);
      case 121:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(7, 29, 15);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000L);
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000000L);
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000L);
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000L);
      case 110:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(8, 7, 15);
         else if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 8;
         }
         return jjMoveStringLiteralDfa9_0(active0, 0x8000100000L);
      case 116:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(8, 35, 15);
         return jjMoveStringLiteralDfa9_0(active0, 0x2001000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000L);
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x4100000L);
      case 101:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(9, 31, 15);
         break;
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000000L);
      case 111:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(9, 24, 7);
         return jjMoveStringLiteralDfa10_0(active0, 0x100000000L);
      case 115:
         return jjMoveStringLiteralDfa10_0(active0, 0x400000L);
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa11_0(active0, 0x4000000L);
      case 108:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(10, 20, 15);
         break;
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000000L);
      case 111:
         return jjMoveStringLiteralDfa11_0(active0, 0x2000000000L);
      case 115:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 39, 15);
         break;
      case 116:
         return jjMoveStringLiteralDfa11_0(active0, 0x2400000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x400000L);
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x2000000000L);
      case 111:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(11, 25, 7);
         break;
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x104000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, 0L);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 99:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(12, 22, 15);
         break;
      case 101:
         return jjMoveStringLiteralDfa13_0(active0, 0x100000000L);
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x4000000L);
      case 115:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 37, 15);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 111:
         return jjMoveStringLiteralDfa14_0(active0, 0x4000000L);
      case 120:
         return jjMoveStringLiteralDfa14_0(active0, 0x100000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 110:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(14, 26, 7);
         break;
      case 116:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(14, 32, 7);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 14;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff800000000000L & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAdd(7);
                  }
                  else if (curChar == 46)
                     jjCheckNAdd(13);
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(9, 10);
                  else if (curChar == 59)
                     jjCheckNAddTwoStates(1, 2);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 14:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(9, 10);
                  else if (curChar == 34)
                  {
                     if (kind > 72)
                        kind = 72;
                  }
                  break;
               case 15:
                  if ((0x3ffa00000000000L & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAdd(7);
                  }
                  else if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 16:
                  if ((0xfffffffffffffbffL & l) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  else if (curChar == 10)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  break;
               case 1:
                  if ((0xfffffffffffffbffL & l) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 2:
                  if (curChar == 10 && kind > 1)
                     kind = 1;
                  break;
               case 4:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 6:
                  if ((0x3ff800000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0x3ffa00000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAdd(7);
                  break;
               case 8:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(9, 10);
                  break;
               case 9:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(9, 10);
                  break;
               case 10:
                  if (curChar == 34 && kind > 72)
                     kind = 72;
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 12:
                  if (curChar == 46)
                     jjCheckNAdd(13);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAdd(13);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAdd(7);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 14:
               case 9:
                  jjCheckNAddTwoStates(9, 10);
                  break;
               case 15:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAdd(7);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 16:
               case 1:
                  jjCheckNAddTwoStates(1, 2);
                  break;
               case 3:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 5:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 70)
                     kind = 70;
                  jjCheckNAddTwoStates(4, 5);
                  break;
               case 6:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAdd(7);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 14:
               case 9:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(9, 10);
                  break;
               case 16:
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 14 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, "\151\156\143\154\165\144\145", 
"\145\170\145\143\165\164\151\157\156", "\164\145\155\160\157\162\141\154", "\143\157\163\164", "\155\141\164\150", 
"\163\145\164\163", "\147\162\141\160\150", "\160\162\157\154\157\147", 
"\144\157\155\141\151\156", "\147\157\141\154", "\164\141\163\153", "\146\151\156\141\154\154\171", 
"\155\151\156\151\172\151\156\143", "\162\145\163\157\165\162\143\145", 
"\143\157\156\144\151\164\151\157\156\141\154", "\143\157\156\144\151\164\151\157\156", 
"\160\162\157\142\141\142\151\154\151\163\164\151\143", "\162\157\163", "\160\165\142\154\151\163\150\55\164\157", 
"\163\165\142\163\143\162\151\142\145\55\164\157", "\162\145\147\151\163\164\145\162\55\141\143\164\151\157\156", 
"\151\163\55\147\157\141\154", "\162\145\163\157\154\166\145\162", "\143\141\160\141\143\151\164\171", 
"\162\145\165\163\141\142\154\145", "\143\157\156\163\165\155\141\142\154\145", 
"\151\156\151\164\151\141\154\55\143\157\156\164\145\170\164", "\143\165\163\164\157\155", "\163\151\155\165\154\141\164\145", 
"\163\164\141\164\145\155\145\156\164", "\157\160\145\162\141\164\157\162", 
"\160\162\145\143\157\156\144\151\164\151\157\156\163", "\145\146\146\145\143\164\163", 
"\143\157\156\163\164\162\141\151\156\164\163", "\50", "\51", "\133", "\135", "\173", "\175", "\174", "\54", "\56", "\72", 
"\72\75", "\73", "\57", "\55\76", "\53", "\55", "\52", "\134", "\42", "\75", "\41\75", 
"\41", "\74", "\74\75", "\76", "\76\75", "\77", "\43", "\44", "\137", null, null, 
null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffffffc1L, 0x3ffL, 
};
static final long[] jjtoSkip = {
   0x3eL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[14];
private final int[] jjstateSet = new int[28];
protected char curChar;
/** Constructor. */
public DomainParser_v4TokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public DomainParser_v4TokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 14; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
