/* Generated By:JavaCC: Do not edit this line. DomainParser_v4.java */
package org.spiderplan.representation.parser.domain_v4;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.Scanner;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.charset.*;
import java.io.IOException;
import java.net.URL;

import org.spiderplan.representation.*;
import org.spiderplan.representation.expressions.*;
import org.spiderplan.representation.expressions.execution.ros.*;
import org.spiderplan.representation.expressions.execution.database.*;
import org.spiderplan.representation.expressions.execution.sockets.*;
import org.spiderplan.representation.expressions.causal.*;
import org.spiderplan.representation.expressions.cost.*;
import org.spiderplan.representation.expressions.optimization.*;
import org.spiderplan.representation.expressions.domain.*;
import org.spiderplan.representation.expressions.execution.*;
import org.spiderplan.representation.expressions.graph.*;
import org.spiderplan.representation.expressions.interaction.*;
import org.spiderplan.representation.expressions.math.*;
import org.spiderplan.representation.expressions.minizinc.*;
import org.spiderplan.representation.expressions.misc.*;
import org.spiderplan.representation.expressions.programs.*;
import org.spiderplan.representation.expressions.prolog.*;
import org.spiderplan.representation.expressions.ontology.*;
import org.spiderplan.representation.expressions.resources.*;
import org.spiderplan.representation.expressions.sampling.*;
import org.spiderplan.representation.expressions.set.*;
import org.spiderplan.representation.expressions.temporal.*;
import org.spiderplan.representation.expressions.configurationPlanning.*;
import org.spiderplan.modules.solvers.Core;
import org.spiderplan.representation.logic.*;
import org.spiderplan.temporal.TemporalNetworkTools;
import org.spiderplan.tools.UniqueID;
@SuppressWarnings("all")

public class DomainParser_v4 implements DomainParser_v4Constants {
        Core c;
        HashMap<Term,ArrayList<Term>> groupMapping = new HashMap<Term,ArrayList<Term>>(); ;
        Map<String,String> includeMapping;
                static public String sourceDirectory;
                static public boolean verbose = true;

  final public void CompilationUnit(Core c, Map<String,String> includeMapping) throws ParseException {
  this.includeMapping = includeMapping;
  this.c = c;
    DomainDefinition();
  }

  final public void DomainDefinition() throws ParseException {
    label_1:
    while (true) {
      if (jj_2_1(2)) {
        InitialContext();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case OP:
          Operator();
          break;
        default:
          jj_la1[0] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OP:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
  }

  final public ArrayList<String> List() throws ParseException {
        ArrayList<String> l = new ArrayList<String>();
        String t;
    jj_consume_token(OBRACE);
    label_2:
    while (true) {
      t = NonComplexTerm();
                                l.add(t);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NON_COMPLEX_TERM:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
    }
    jj_consume_token(CBRACE);
                {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public void InitialContext() throws ParseException {
        ConstraintDatabase cDB;
        if ( verbose ) { System.out.println("[Parser] Initial Context"); }
    jj_consume_token(OP);
    jj_consume_token(INITIAL);
    cDB = ConstraintDatabase();
    jj_consume_token(CP);
                        c.getContext().add(cDB);
  }

/**
 * Terms and Terms
 */
  final public String NonComplexTerm() throws ParseException {
        Token part;
        String r = "";
    part = jj_consume_token(NON_COMPLEX_TERM);
                {if (true) return part.image;}
    throw new Error("Missing return statement in function");
  }

  final public Term Term() throws ParseException {
        Term result;
        Term arg;
        Term[] args;
        ArrayList<Term> argList = new ArrayList<Term>();
        String name;
        Term lowerBound, upperBound;
        String tmpStr = "";
        boolean isVariable = false;
        Double val;
        Token t;
    if (jj_2_2(5)) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case QPOINT:
        jj_consume_token(QPOINT);
                         isVariable = true;
        break;
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      name = NonComplexTerm();
                  if ( !isVariable )
                          result = Term.parse(name);
                      else
                          result = Term.createVariable(name);
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        t = jj_consume_token(STRING);
          result = Term.createConstant(t.image);
        break;
      case OP:
        jj_consume_token(OP);
        name = NonComplexTerm();
        label_3:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OP:
          case OBRACKET:
          case OBRACE:
          case QPOINT:
          case NON_COMPLEX_TERM:
          case STRING:
            ;
            break;
          default:
            jj_la1[4] = jj_gen;
            break label_3;
          }
          arg = Term();
                                         argList.add(arg);
        }
        jj_consume_token(CP);
                    args = new Term[argList.size()];
                    for ( int i = 0 ; i < argList.size(); i++ )
                    {
                      args[i] = argList.get(i);
                    }
                        result = Term.createComplex(name,args);
        break;
      case OBRACE:
        jj_consume_token(OBRACE);
        label_4:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OP:
          case OBRACKET:
          case OBRACE:
          case QPOINT:
          case NON_COMPLEX_TERM:
          case STRING:
            ;
            break;
          default:
            jj_la1[5] = jj_gen;
            break label_4;
          }
          arg = Term();
                                          argList.add(arg);
        }
        jj_consume_token(CBRACE);
                    args = new Term[argList.size()];
                    for ( int i = 0 ; i < argList.size(); i++ )
                    {
                      args[i] = argList.get(i);
                    }
                        result = Term.createComplex("list",args);
        break;
      case OBRACKET:
        jj_consume_token(OBRACKET);
        lowerBound = Term();
        upperBound = Term();
        jj_consume_token(CBRACKET);
                                result = Term.createComplex("interval", lowerBound, upperBound);
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return result;}
    throw new Error("Missing return statement in function");
  }

/**
 *	STATEMENT
 */
  final public Statement Statement() throws ParseException {
    Term intervalKey;
    Term v = null;
    Term x;
    jj_consume_token(OP);
    intervalKey = IntervalTerm();
    x = Term();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OP:
    case OBRACKET:
    case OBRACE:
    case QPOINT:
    case NON_COMPLEX_TERM:
    case STRING:
      v = Term();
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    jj_consume_token(CP);
                if ( v != null )
                {
                        {if (true) return new Statement( intervalKey, x, v );}
                } else {
                        {if (true) return new Statement( intervalKey, x, Term.createConstant("true") );}
                }
    throw new Error("Missing return statement in function");
  }

/**
 * Constraints
 */
  final public ConstraintDatabase ConstraintDatabase() throws ParseException {
  Expression c;
  Term programID;
  ConstraintDatabase cDB = new ConstraintDatabase();
  //groupMapping = new HashMap<Term,ArrayList<Term>>();
  Term name;
    label_5:
    while (true) {
      if (jj_2_3(2)) {
        ;
      } else {
        break label_5;
      }
      jj_consume_token(OP);
      if (jj_2_23(2)) {
        jj_consume_token(TEMPORAL);
        label_6:
        while (true) {
          c = TemporalConstraint();
                                                                                                  cDB.add(c);
          if (jj_2_4(2)) {
            ;
          } else {
            break label_6;
          }
        }
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COST:
          jj_consume_token(COST);
          label_7:
          while (true) {
            c = CostConstraint();
                                                                                                  cDB.add(c);
            if (jj_2_5(2)) {
              ;
            } else {
              break label_7;
            }
          }
          break;
        case OPTIMIZATION:
          jj_consume_token(OPTIMIZATION);
          label_8:
          while (true) {
            c = OptimizationExpression();
                                                                                                          cDB.add(c);
            if (jj_2_6(2)) {
              ;
            } else {
              break label_8;
            }
          }
          break;
        case RESOURCE:
          jj_consume_token(RESOURCE);
          label_9:
          while (true) {
            c = ResourceConstraint();
                                                                                                  cDB.add(c);
            if (jj_2_7(2)) {
              ;
            } else {
              break label_9;
            }
          }
          break;
        case GRAPH:
          jj_consume_token(GRAPH);
          label_10:
          while (true) {
            c = GraphConstraint();
                                                                                                  cDB.add(c);
            if (jj_2_8(2)) {
              ;
            } else {
              break label_10;
            }
          }
          break;
        case GOAL:
          jj_consume_token(GOAL);
          label_11:
          while (true) {
            c = GoalConstraint();
                                                                                                  cDB.add(c);
            if (jj_2_9(2)) {
              ;
            } else {
              break label_11;
            }
          }
          break;
        case TASK:
          jj_consume_token(TASK);
          label_12:
          while (true) {
            c = TaskConstraint();
                                                                                                  cDB.add(c);
            if (jj_2_10(2)) {
              ;
            } else {
              break label_12;
            }
          }
          break;
        case OBSERVATION:
          jj_consume_token(OBSERVATION);
          label_13:
          while (true) {
            c = Observation();
                                                                                                          cDB.add(c);
            if (jj_2_11(2)) {
              ;
            } else {
              break label_13;
            }
          }
          break;
        case FINALLY:
          jj_consume_token(FINALLY);
          c = FinallyConstraint();
                                                                                                                  cDB.add(c);
          break;
        case DOMAIN:
          jj_consume_token(DOMAIN);
          label_14:
          while (true) {
            c = DomainConstraint();
                                                                                                  cDB.add(c);
            if (jj_2_12(2)) {
              ;
            } else {
              break label_14;
            }
          }
          break;
        case SAMPLING:
          jj_consume_token(SAMPLING);
          label_15:
          while (true) {
            c = SamplingConstraint();
                                                                                  cDB.add(c);
            if (jj_2_13(2)) {
              ;
            } else {
              break label_15;
            }
          }
          break;
        case CONFIGURATIONPLANNING:
          jj_consume_token(CONFIGURATIONPLANNING);
          label_16:
          while (true) {
            c = ConfigurationPlanningConstraint();
                                                                                                          cDB.add(c);
            if (jj_2_14(2)) {
              ;
            } else {
              break label_16;
            }
          }
          break;
        case MATH:
          jj_consume_token(MATH);
          label_17:
          while (true) {
            c = MathConstraint();
                                                                                                  cDB.add(c);
            if (jj_2_15(2)) {
              ;
            } else {
              break label_17;
            }
          }
          break;
        case SET:
          jj_consume_token(SET);
          label_18:
          while (true) {
            c = SetConstraint();
                                                                                                          cDB.add(c);
            if (jj_2_16(2)) {
              ;
            } else {
              break label_18;
            }
          }
          break;
        case CONDITIONAL:
        case IC:
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case CONDITIONAL:
            jj_consume_token(CONDITIONAL);
            break;
          case IC:
            jj_consume_token(IC);
            break;
          default:
            jj_la1[8] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          c = ConditionalConstraint();
                                                                                                          cDB.add(c);
          break;
        case SIMULATE:
          jj_consume_token(SIMULATE);
          c = Simulation();
                                                                                                  cDB.add(c);
          break;
        case ROS:
          jj_consume_token(ROS);
          label_19:
          while (true) {
            c = ROSConstraint();
                                                                                                                  cDB.add(c);
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case OP:
              ;
              break;
            default:
              jj_la1[9] = jj_gen;
              break label_19;
            }
          }
          break;
        case DBEXEC:
          jj_consume_token(DBEXEC);
          label_20:
          while (true) {
            c = DatabaseExecutionExpression();
                                                                                                                                  cDB.add(c);
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case OP:
            case OBRACKET:
            case OBRACE:
            case QPOINT:
            case NON_COMPLEX_TERM:
            case STRING:
              ;
              break;
            default:
              jj_la1[10] = jj_gen;
              break label_20;
            }
          }
          break;
        case SOCKETS:
          jj_consume_token(SOCKETS);
          label_21:
          while (true) {
            c = SocketExpression();
                                                                                                                                  cDB.add(c);
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case OP:
            case OBRACKET:
            case OBRACE:
            case QPOINT:
            case NON_COMPLEX_TERM:
            case STRING:
              ;
              break;
            default:
              jj_la1[11] = jj_gen;
              break label_21;
            }
          }
          break;
        case INCLUDE:
          jj_consume_token(INCLUDE);
          label_22:
          while (true) {
            c = IncludeProgram();
                                                                                                  cDB.add(c);
            if (jj_2_17(2)) {
              ;
            } else {
              break label_22;
            }
          }
          break;
        case STATEMENT:
          jj_consume_token(STATEMENT);
          label_23:
          while (true) {
            c = Statement();
                                                                                                          cDB.add(c);
            if (jj_2_18(2)) {
              ;
            } else {
              break label_23;
            }
          }
          break;
        case PROLOG:
          jj_consume_token(PROLOG);
          programID = Term();
          label_24:
          while (true) {
            c = PrologConstraint(programID);
                                                                                                          cDB.add(c);
            if (jj_2_19(2)) {
              ;
            } else {
              break label_24;
            }
          }
          break;
        case ONTOLOGY:
          jj_consume_token(ONTOLOGY);
          programID = Term();
          label_25:
          while (true) {
            c = OntologyExpression(programID);
                                                                                                                  cDB.add(c);
            if (jj_2_20(2)) {
              ;
            } else {
              break label_25;
            }
          }
          break;
        case SPARQL:
          jj_consume_token(SPARQL);
          label_26:
          while (true) {
            c = SparQLQuery();
                                                                          cDB.add(c);
            if (jj_2_21(2)) {
              ;
            } else {
              break label_26;
            }
          }
          break;
        case MINIZINC:
          jj_consume_token(MINIZINC);
          programID = Term();
          label_27:
          while (true) {
            c = MiniZincInput(programID);
                                                                                                          cDB.add(c);
            if (jj_2_22(2)) {
              ;
            } else {
              break label_27;
            }
          }
          break;
        case ASSERTION:
          jj_consume_token(ASSERTION);
          c = Assertion();
                                                          cDB.add(c);
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(CP);
    }
                TemporalNetworkTools.replaceGroupKeys(cDB, groupMapping);
                {if (true) return cDB;}
    throw new Error("Missing return statement in function");
  }

  final public Expression TemporalConstraint() throws ParseException {
        Term constraint;
    constraint = Term();
                if ( verbose ) { System.out.println("[Parser] Temporal Constraint"); }
                String name = constraint.getName().replace("-","").toLowerCase();
                if ( name.equals("planninginterval") ) {
                  if ( constraint.getNumArgs() == 1 ) {
                     {if (true) return new PlanningInterval(constraint.getArg(0));}
              } else {
                 {if (true) return new PlanningInterval(constraint.getArg(0), constraint.getArg(1));}
              }
            } else if (  constraint.getName().equals("date-time-reference") ) {
                                        {if (true) return new DateTimeReference(constraint);}
            } else if ( name.equals("possibleintersection") || name.equals("intersection") ) {
              ArrayList<Term> terms = new ArrayList<Term>();
          for ( int i = 0 ; i < constraint.getNumArgs() ; i++ )
          {
                            terms.add(constraint.getArg(i));
          }
              {if (true) return new PossibleIntersection(terms);}
                        } else if ( name.equals("distance") ) {
                                {if (true) return new SimpleDistanceConstraint( constraint );}
            } else if ( name.contains("greater") || name.contains("less") ) {
                  {if (true) return new TemporalIntervalQuery( constraint );}
            } else {
              {if (true) return new AllenConstraint( constraint );}
            }
    throw new Error("Missing return statement in function");
  }

  final public Expression PrologConstraint(Term programID) throws ParseException {
        Term constraint;
    constraint = Term();
                        if ( verbose ) { System.out.println("[Parser] Prolog Constraint"); }
                        {if (true) return new PrologConstraint( constraint, programID );}
    throw new Error("Missing return statement in function");
  }

  final public Expression ConfigurationPlanningConstraint() throws ParseException {
        Term constraint;
    constraint = Term();
                        if ( verbose ) { System.out.println("[Parser] Configuration Planning Constraint"); }
                  {if (true) return new ConfigurationPlanningConstraint( constraint );}
    throw new Error("Missing return statement in function");
  }

  final public Expression GoalConstraint() throws ParseException {
        Statement g;
    g = Statement();
                if ( verbose ) { System.out.println("[Parser] Goal Constraint"); }
                {if (true) return new OpenGoal(g);}
    throw new Error("Missing return statement in function");
  }

  final public Expression TaskConstraint() throws ParseException {
        Statement task;
    task = Statement();
                if ( verbose ) { System.out.println("[Parser] Task Constraint"); }
                {if (true) return new Task(task);}
    throw new Error("Missing return statement in function");
  }

  final public Expression Observation() throws ParseException {
        Statement observation;
    observation = Statement();
                if ( verbose ) { System.out.println("[Parser] Observation"); }
                {if (true) return new Observation(observation);}
    throw new Error("Missing return statement in function");
  }

  final public Expression MiniZincInput(Term programID) throws ParseException {
        Term constraint;
    constraint = Term();
                if ( verbose ) { System.out.println("[Parser] MiniZinc Constraint"); }
                {if (true) return new MiniZincInput( constraint, programID );}
    throw new Error("Missing return statement in function");
  }

  final public Expression SparQLQuery() throws ParseException {
        List<Term> targetVariables = new ArrayList<Term>();
        Term programID;
        Term modelID;
        Term tmp;
    jj_consume_token(OP);
    programID = Term();
    modelID = Term();
    label_28:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OP:
      case OBRACKET:
      case OBRACE:
      case QPOINT:
      case NON_COMPLEX_TERM:
      case STRING:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_28;
      }
      tmp = Term();
                        targetVariables.add(tmp);
    }
    jj_consume_token(CP);
                if ( verbose ) { System.out.println("[Parser] SparQLQuery"); }
          {if (true) return new SparQLQuery( targetVariables, programID, modelID );}
    throw new Error("Missing return statement in function");
  }

  final public Expression GraphConstraint() throws ParseException {
        Term constraint;
    constraint = Term();
                if ( verbose ) { System.out.println("[Parser] Graph Constraint"); }
                {if (true) return new GraphConstraint( constraint );}
    throw new Error("Missing return statement in function");
  }

  final public Expression MathConstraint() throws ParseException {
        Term constraint;
    constraint = Term();
                {if (true) return new MathConstraint( constraint );}
    throw new Error("Missing return statement in function");
  }

  final public Expression SetConstraint() throws ParseException {
        Term constraint;
    constraint = Term();
                if ( verbose ) { System.out.println("[Parser] Set Constraint"); }
                {if (true) return new SetConstraint( constraint );}
    throw new Error("Missing return statement in function");
  }

  final public Expression SamplingConstraint() throws ParseException {
        Term constraint;
    constraint = Term();
                if ( verbose ) { System.out.println("[Parser] Probabilistic Constraint"); }
                {if (true) return new SamplingConstraint( constraint );}
    throw new Error("Missing return statement in function");
  }

  final public Expression FinallyConstraint() throws ParseException {
        Term id;
        ConstraintDatabase cDB;
    id = Term();
    cDB = ConstraintDatabase();
                if ( verbose ) { System.out.println("[Parser] Finally Constraint"); }
                {if (true) return new Finally(id, cDB);}
    throw new Error("Missing return statement in function");
  }

  final public Expression DomainConstraint() throws ParseException {
        Term constraint;
    constraint = Term();
                if ( verbose ) { System.out.println("[Parser] Domain Constraint"); }
                if ( constraint.getName().equals("enum") ) {
                        {if (true) return new TypeDomainConstraint(constraint);}
                } else if ( constraint.getName().equals("float") ) {
                        {if (true) return new TypeDomainConstraint(constraint);}
                } else if ( constraint.getName().equals("unrestricted") ) {
                        {if (true) return new TypeDomainConstraint(constraint);}
                } else if ( constraint.getName().equals("int") ) {
                        {if (true) return new TypeDomainConstraint(constraint);}
                } else if ( constraint.getName().equals("sig") ) {
                        Term varSigTerm = constraint.getArg(0);
                        Term valSigTerm = null;
                        if ( constraint.getNumArgs() > 1 ) {
                                valSigTerm = constraint.getArg(1);
                        }
            Term[] args = new Term[varSigTerm.getNumArgs()];
            for ( int i = 0 ; i < args.length ; i++ ) {
                args[i] = varSigTerm.getArg(i);
            }
                        Term varSig = Term.createComplex(varSigTerm.getName(),args);
                        if ( valSigTerm != null ) {
                                {if (true) return new TypeSignatureConstraint(varSig,valSigTerm);}
                        } else {
                                {if (true) return new TypeSignatureConstraint(varSig);}
                        }

                } else if ( constraint.getName().equals("new-object") ) {
                        {if (true) return new NewObject(constraint.getArg(0), constraint.getArg(1));}
                } else if ( constraint.getName().equals("uncontrollable") ) {
                        {if (true) return new Uncontrollable(constraint);}
                } else if ( constraint.getName().equals("in") || constraint.getName().equals("not-in")) {
                        ArrayList<Term> D = new ArrayList<Term>();
                        for ( int i = 1 ; i < constraint.getNumArgs() ; i++ ) {
                                Term t = constraint.getArg(i);
                                if ( t.isComplex() && t.nameEquals(Term.createConstant("list") ) ) {
                    for ( int j = 0 ; j < t.getNumArgs() ; j++  ) {
                       D.add(t.getArg(j));
                    }
                                }
                        }
                        Term[] dom = new Term[D.size()];
                        for ( int i = 0 ; i < D.size() ; i++ ) {
                                dom[i] = D.get(i);
                        }
                        Term list = Term.createComplex("list", dom);

                        Term a = Term.createComplex(constraint.getName(), constraint.getArg(0), list);

                        {if (true) return new DomainMemberConstraint(a);}
                } else {
                        {if (true) return new DomainMemberConstraint(constraint);}
                }
    throw new Error("Missing return statement in function");
  }

  final public Expression ConditionalConstraint() throws ParseException {
        InteractionConstraint iC;
        ConstraintDatabase tDB;
        Term name;
        if ( verbose ) { System.out.println("[Parser] Interaction Constraint"); }
    name = Term();
                iC = new InteractionConstraint(name);
    jj_consume_token(OP);
    jj_consume_token(CONDITION);
    tDB = ConstraintDatabase();
                        iC.setCondition(tDB);
    jj_consume_token(CP);
    label_29:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OP:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_29;
      }
      jj_consume_token(OP);
      jj_consume_token(RESOLVER);
      tDB = ConstraintDatabase();
                        iC.addResolver(tDB);
      jj_consume_token(CP);
    }
                        {if (true) return iC;}
    throw new Error("Missing return statement in function");
  }

  final public Expression ROSConstraint() throws ParseException {
        Expression rosCon;
        Term variable;
        Term value;
        Term topic;
        Term msgType;

        Term serverID, actionName;
        Term resultMsg = null;

        if ( verbose ) { System.out.println("[Parser] ROS Constraint"); }
    jj_consume_token(OP);
    if (jj_2_25(2)) {
      jj_consume_token(ROSPUBLISH);
      variable = Term();
      value = Term();
      topic = Term();
      msgType = Term();
                          rosCon = new ROSConstraint(ExpressionTypes.ROSRelation.Publish,variable,value,topic,msgType);
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ROSSUBSCRIBE:
        jj_consume_token(ROSSUBSCRIBE);
        variable = Term();
        value = Term();
        topic = Term();
        msgType = Term();
                          rosCon = new ROSConstraint(ExpressionTypes.ROSRelation.Subscribe,variable,value,topic,msgType);
        break;
      case ROSGOAL:
        jj_consume_token(ROSGOAL);
        variable = Term();
        serverID = Term();
        actionName = Term();
        msgType = Term();
        if (jj_2_24(2)) {
          resultMsg = Term();
        } else {
          ;
        }
                          rosCon = new ROSGoal(variable,serverID,actionName,msgType,resultMsg);
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(CP);
          {if (true) return rosCon;}
    throw new Error("Missing return statement in function");
  }

  final public Expression DatabaseExecutionExpression() throws ParseException {
  Term name;
        if ( verbose ) { System.out.println("[Parser] Setting Capacity"); }
    name = Term();
                {if (true) return new DatabaseExecutionExpression(name);}
    throw new Error("Missing return statement in function");
  }

  final public Expression Simulation() throws ParseException {
        Simulation sC;
        Term dispatchTime;
        ConstraintDatabase simDB;
        Token type;
        if ( verbose ) { System.out.println("[Parser] Simulation Constraint"); }
    dispatchTime = Term();
    simDB = ConstraintDatabase();
                {if (true) return new Simulation(dispatchTime,simDB);}
    throw new Error("Missing return statement in function");
  }

  final public Expression ReusableResourceCapacity() throws ParseException {
        Term name;
        String cap;
        if ( verbose ) { System.out.println("[Parser] Setting Capacity"); }
    jj_consume_token(OP);
    jj_consume_token(REUSABLE);
    name = Term();
    cap = NonComplexTerm();
    jj_consume_token(CP);
                {if (true) return new ReusableResourceCapacity(name, Integer.valueOf(cap));}
    throw new Error("Missing return statement in function");
  }

  final public Expression IncludeProgram() throws ParseException {
        Term name;
    String includedProgramID;
                String subStart = null;
                String subEnd = null;
    Token includedProgramFile;
    if ( verbose ) { System.out.println("[Parser] Include Program"); }
    if (jj_2_26(4)) {
      jj_consume_token(OP);
      name = Term();
      includedProgramFile = jj_consume_token(STRING);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        subStart = jj_consume_token(STRING).image;
        subEnd = jj_consume_token(STRING).image;
        break;
      default:
        jj_la1[16] = jj_gen;
        ;
      }
      jj_consume_token(CP);
                try {
                        String fileName = includedProgramFile.image.substring(1,includedProgramFile.image.length()-1);

                        if ( fileName.startsWith("http://") ) {
                                        Scanner scanner = new Scanner(new URL(fileName).openStream(), "UTF-8");
                                        String program = scanner.useDelimiter("\u005c\u005cA").next();
                                        scanner.close();
                                        if ( subStart == null )
                                                 {if (true) return new IncludedProgram(name, fileName, program );}
                                        else
                                                 {if (true) return new IncludedProgram(name, fileName, program, subStart, subEnd );}

                        } else {
                                if ( fileName.startsWith(".") ) {
                                        fileName = sourceDirectory + fileName;
                                        fileName = fileName.replace("/./", "/");
                                }

                                String program = new String(Files.readAllBytes(Paths.get(fileName)), StandardCharsets.UTF_8);

                                if ( subStart == null )
                                                 {if (true) return new IncludedProgram(name, fileName, program );}
                                else
                                                 {if (true) return new IncludedProgram(name, fileName, program, subStart, subEnd );}

                        }
                } catch ( IOException e ) {
                        e.printStackTrace();
                        System.exit(0);
                }
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OP:
        jj_consume_token(OP);
        name = Term();
        includedProgramID = NonComplexTerm();
        jj_consume_token(CP);
            {if (true) return new IncludedProgram(name, includeMapping.get(includedProgramID) );}
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public Expression Assertion() throws ParseException {
        ArrayList<Term> parameters = new ArrayList<Term>();
        Term parameter;
        Term expressionType;
         if ( verbose ) { System.out.println("[Parser] Assertion"); }
    expressionType = Term();
    label_30:
    while (true) {
      parameter = Term();
                                                                    parameters.add(parameter);
      if (jj_2_27(2)) {
        ;
      } else {
        break label_30;
      }
    }
                        Term list[] = new Term[parameters.size()];
                        for ( int i = 0 ; i < parameters.size() ; i++ ) {
                                list[i] = parameters.get(i);
                        }

                {if (true) return new Assertion( expressionType, list );}
    throw new Error("Missing return statement in function");
  }

/**
 * Operators
 */
  final public void Operator() throws ParseException {
    Operator o;
    List<Term> sigTerms = new ArrayList<Term>();
    Term name = null;
    Term arg = null;
    Statement s;
    ConstraintDatabase C;

    if ( verbose ) { System.out.println("[Parser] Operator"); }
    jj_consume_token(OP);
    jj_consume_token(OPERATOR);
    name = Term();
                        o = new Operator();
                        o.setName( name );
                        //groupMapping = new HashMap<Term,ArrayList<Term>>();

    if (jj_2_28(2)) {
      jj_consume_token(OP);
      jj_consume_token(SIGNATURE);
                        String opName = name.getName();
                        int i = 0;
                        Term[] args = new Term[name.getNumArgs()];
      label_31:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case OP:
        case OBRACKET:
        case OBRACE:
        case QPOINT:
        case NON_COMPLEX_TERM:
        case STRING:
          ;
          break;
        default:
          jj_la1[18] = jj_gen;
          break label_31;
        }
        arg = Term();
                                if ( i >= args.length ) {
                                        System.err.println("Signature has more arguments than name of operator " + name + ". Exiting...");
                                        System.exit(1);
                                }
                                args[i++] = arg;
      }
                        if ( i != name.getNumArgs() ) {
                                System.err.println("Signature has less arguments than name of operator " + name + ". Exiting...");
                                System.exit(1);
                        }
                        Term sig = Term.createComplex(opName, args);
                        c.getContext().add(new TypeSignatureConstraint(sig));
      jj_consume_token(CP);
    } else {
      ;
    }
    jj_consume_token(OP);
    jj_consume_token(PRECONDITIONS);
    label_32:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OP:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_32;
      }
      s = Statement();
                                                     o.addPrecondition(s);
    }
    jj_consume_token(CP);
    jj_consume_token(OP);
    jj_consume_token(EFFECTS);
    label_33:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OP:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_33;
      }
      s = Statement();
                                                     o.addEffect(s);
    }
    jj_consume_token(CP);
    jj_consume_token(OP);
    jj_consume_token(CONSTRAINTS);
    C = ConstraintDatabase();
    jj_consume_token(CP);
          o.addConstraints(C);
          TemporalNetworkTools.replaceGroupKeys(o.getConstraints(), groupMapping);
          c.getOperators().add(o);
    jj_consume_token(CP);
  }

  final public Term IntervalTerm() throws ParseException {
        String group = "";
        List<Term> groups = new ArrayList<Term>();
        Term keyTerm = null;
        Token keyToken;
        String keyString = null;
    if (jj_2_29(2)) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NON_COMPLEX_TERM:
        keyString = NonComplexTerm();
        break;
      case QPOINT:
        jj_consume_token(QPOINT);
        keyString = NonComplexTerm();
                                                                keyString = "?" + keyString;
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } else {
      ;
    }
    label_34:
    while (true) {
      if (jj_2_30(2)) {
        ;
      } else {
        break label_34;
      }
      jj_consume_token(BAR);
      group = NonComplexTerm();
          groups.add(Term.parse(group));
    }
                if ( keyString == null )
                keyTerm = Term.createConstant("key" + UniqueID.getID());
            else
                keyTerm = Term.parse(keyString);

                for ( Term groupTerm : groups )
                {
                        if ( !groupMapping.containsKey(groupTerm) )
                        {
                                groupMapping.put(groupTerm, new ArrayList<Term>());
                        }
                        groupMapping.get(groupTerm).add(keyTerm);
           }
           {if (true) return keyTerm;}
    throw new Error("Missing return statement in function");
  }

  final public Expression ResourceConstraint() throws ParseException {
        Expression c;
    c = ReusableResourceCapacity();
                                             {if (true) return c;}
    throw new Error("Missing return statement in function");
  }

  final public Expression CostConstraint() throws ParseException {
        Term cRel;
    cRel = Term();
                                        {if (true) return new Cost(cRel);}
    throw new Error("Missing return statement in function");
  }

  final public Expression OptimizationExpression() throws ParseException {
        Term cRel;
    cRel = Term();
                                        {if (true) return new OptimizationTarget(cRel);}
    throw new Error("Missing return statement in function");
  }

  final public Expression SocketExpression() throws ParseException {
        Term cRel;
    cRel = Term();
                                        {if (true) return new SocketExpression(cRel);}
    throw new Error("Missing return statement in function");
  }

  final public Expression OntologyExpression(Term programID) throws ParseException {
        Term constraint;
    constraint = Term();
                if ( verbose ) { System.out.println("[Parser] Ontology Expression"); }
                {if (true) return new OntologyExpression( programID, constraint );}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  private boolean jj_3_9() {
    if (jj_3R_68()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_67()) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_66()) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_3R_72()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_64()) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_scan_token(ASSERTION)) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_scan_token(MINIZINC)) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_scan_token(SPARQL)) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_scan_token(ONTOLOGY)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(PROLOG)) return true;
    return false;
  }

  private boolean jj_3R_71() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(STATEMENT)) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_scan_token(INCLUDE)) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_scan_token(SOCKETS)) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_scan_token(DBEXEC)) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_scan_token(ROS)) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(SIMULATE)) return true;
    return false;
  }

  private boolean jj_3R_51() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(23)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) return true;
    }
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_scan_token(SET)) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(MATH)) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_scan_token(CONFIGURATIONPLANNING)) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(SAMPLING)) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_scan_token(DOMAIN)) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_scan_token(FINALLY)) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(OBSERVATION)) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_scan_token(TASK)) return true;
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(GOAL)) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_scan_token(GRAPH)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(RESOURCE)) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(OPTIMIZATION)) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_scan_token(COST)) return true;
    return false;
  }

  private boolean jj_3R_79() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3_23() {
    if (jj_scan_token(TEMPORAL)) return true;
    Token xsp;
    if (jj_3_4()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_4()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_72() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_76() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_26()) {
    jj_scanpos = xsp;
    if (jj_3R_87()) return true;
    }
    return false;
  }

  private boolean jj_3_26() {
    if (jj_scan_token(OP)) return true;
    if (jj_3R_82()) return true;
    if (jj_scan_token(STRING)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_83()) jj_scanpos = xsp;
    if (jj_scan_token(CP)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(OP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_23()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_75() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_86() {
    if (jj_scan_token(OP)) return true;
    if (jj_scan_token(REUSABLE)) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_74() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_3R_86()) return true;
    return false;
  }

  private boolean jj_3R_77() {
    if (jj_scan_token(OP)) return true;
    if (jj_3R_88()) return true;
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_85() {
    if (jj_scan_token(QPOINT)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3R_84() {
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3R_80() {
    if (jj_scan_token(OP)) return true;
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_93() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_92() {
    if (jj_scan_token(OBRACKET)) return true;
    if (jj_3R_82()) return true;
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3_30() {
    if (jj_scan_token(BAR)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3_29() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_84()) {
    jj_scanpos = xsp;
    if (jj_3R_85()) return true;
    }
    return false;
  }

  private boolean jj_3R_81() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3_25() {
    if (jj_scan_token(ROSPUBLISH)) return true;
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_94() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_91() {
    if (jj_scan_token(OBRACE)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_93()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(CBRACE)) return true;
    return false;
  }

  private boolean jj_3R_88() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_29()) jj_scanpos = xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_70() {
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_90() {
    if (jj_scan_token(OP)) return true;
    if (jj_3R_37()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_94()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(CP)) return true;
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_89() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(QPOINT)) return true;
    return false;
  }

  private boolean jj_3_2() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3R_68() {
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_82() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3R_89()) {
    jj_scanpos = xsp;
    if (jj_3R_90()) {
    jj_scanpos = xsp;
    if (jj_3R_91()) {
    jj_scanpos = xsp;
    if (jj_3R_92()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_73() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3_28() {
    if (jj_scan_token(OP)) return true;
    if (jj_scan_token(SIGNATURE)) return true;
    return false;
  }

  private boolean jj_3R_78() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3_27() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3_20() {
    if (jj_3R_79()) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_scan_token(NON_COMPLEX_TERM)) return true;
    return false;
  }

  private boolean jj_3_22() {
    if (jj_3R_81()) return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_3R_78()) return true;
    return false;
  }

  private boolean jj_3R_83() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(OP)) return true;
    if (jj_scan_token(INITIAL)) return true;
    return false;
  }

  private boolean jj_3_18() {
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_3R_76()) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_3R_73()) return true;
    return false;
  }

  private boolean jj_3_21() {
    if (jj_3R_80()) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_3R_70()) return true;
    return false;
  }

  private boolean jj_3_16() {
    if (jj_3R_75()) return true;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_3R_74()) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_3R_71()) return true;
    return false;
  }

  private boolean jj_3R_87() {
    if (jj_scan_token(OP)) return true;
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3_24() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_69()) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_3R_82()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public DomainParser_v4TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[22];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1800000,0x0,0x0,0x0,0x3dfffe40,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x8000,0x8000,0x1000000,0x400000,0x34a8000,0x34a8000,0x20a8000,0x34a8000,0x0,0x8000,0x34a8000,0x34a8000,0x6086,0x34a8000,0x8000,0xc00,0x2000000,0x8000,0x34a8000,0x8000,0x8000,0x1400000,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[30];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public DomainParser_v4(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public DomainParser_v4(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new DomainParser_v4TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public DomainParser_v4(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new DomainParser_v4TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public DomainParser_v4(DomainParser_v4TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(DomainParser_v4TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        exists = true;
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[58];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 22; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 58; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 30; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
